name: .NET Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Скачиваем код проекта
      uses: actions/checkout@v4

    - name: Настраиваем .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'

    - name: Восстанавливаем зависимости (Nuget)
      run: dotnet restore ClothingStoreWeb.sln

    - name: Собираем проект (Проверка на ошибки компиляции)
      run: dotnet build ClothingStoreWeb.sln --no-restore

    - name: Запускаем тесты (Если они у вас написаны)
      run: dotnet test ClothingStoreWeb.sln --no-build --verbosity normal
